//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesEntities : DbContext
    {
        public MoviesEntities()
            : base("name=MoviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblActor> tblActors { get; set; }
        public virtual DbSet<tblAudio> tblAudios { get; set; }
        public virtual DbSet<tblCodec> tblCodecs { get; set; }
        public virtual DbSet<tblComposer> tblComposers { get; set; }
        public virtual DbSet<tblDirector> tblDirectors { get; set; }
        public virtual DbSet<tblEpisode> tblEpisodes { get; set; }
        public virtual DbSet<tblEpisodeMediaAudio> tblEpisodeMediaAudios { get; set; }
        public virtual DbSet<tblEpisodeMediaCodec> tblEpisodeMediaCodecs { get; set; }
        public virtual DbSet<tblEpisodeMediaReleaseType> tblEpisodeMediaReleaseTypes { get; set; }
        public virtual DbSet<tblEpisodeMediaResolution> tblEpisodeMediaResolutions { get; set; }
        public virtual DbSet<tblEpisodeMediaSpecial> tblEpisodeMediaSpecials { get; set; }
        public virtual DbSet<tblGenre> tblGenres { get; set; }
        public virtual DbSet<tblMedia> tblMedias { get; set; }
        public virtual DbSet<tblMovie> tblMovies { get; set; }
        public virtual DbSet<tblMusic> tblMusics { get; set; }
        public virtual DbSet<tblNetwork> tblNetworks { get; set; }
        public virtual DbSet<tblParentalRating> tblParentalRatings { get; set; }
        public virtual DbSet<tblPerson> tblPersons { get; set; }
        public virtual DbSet<tblProducer> tblProducers { get; set; }
        public virtual DbSet<tblReleaseType> tblReleaseTypes { get; set; }
        public virtual DbSet<tblResolution> tblResolutions { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSpecial> tblSpecials { get; set; }
        public virtual DbSet<tblStudio> tblStudios { get; set; }
        public virtual DbSet<tblTVSery> tblTVSeries { get; set; }
        public virtual DbSet<tblTVSeriesMediaAudio> tblTVSeriesMediaAudios { get; set; }
        public virtual DbSet<tblTVSeriesMediaCodec> tblTVSeriesMediaCodecs { get; set; }
        public virtual DbSet<tblTVSeriesMediaReleaseType> tblTVSeriesMediaReleaseTypes { get; set; }
        public virtual DbSet<tblTVSeriesMediaResolution> tblTVSeriesMediaResolutions { get; set; }
        public virtual DbSet<tblTVSeriesMediaSpecial> tblTVSeriesMediaSpecials { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<qryActor> qryActors { get; set; }
        public virtual DbSet<qryAudio> qryAudios { get; set; }
        public virtual DbSet<qryCodec> qryCodecs { get; set; }
        public virtual DbSet<qryDirector> qryDirectors { get; set; }
        public virtual DbSet<qryGenre> qryGenres { get; set; }
        public virtual DbSet<qryMedia> qryMedias { get; set; }
        public virtual DbSet<qryParentalRating> qryParentalRatings { get; set; }
        public virtual DbSet<qryReleaseType> qryReleaseTypes { get; set; }
        public virtual DbSet<qryResolution> qryResolutions { get; set; }
        public virtual DbSet<qrySpecial> qrySpecials { get; set; }
    }
}
