//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMedia()
        {
            this.tblEpisodeMediaAudios = new HashSet<tblEpisodeMediaAudio>();
            this.tblEpisodeMediaCodecs = new HashSet<tblEpisodeMediaCodec>();
            this.tblEpisodeMediaReleaseTypes = new HashSet<tblEpisodeMediaReleaseType>();
            this.tblEpisodeMediaResolutions = new HashSet<tblEpisodeMediaResolution>();
            this.tblEpisodeMediaSpecials = new HashSet<tblEpisodeMediaSpecial>();
            this.tblTVSeries = new HashSet<tblTVSery>();
            this.tblMovies = new HashSet<tblMovie>();
            this.tblTVSeriesMediaAudios = new HashSet<tblTVSeriesMediaAudio>();
            this.tblTVSeriesMediaCodecs = new HashSet<tblTVSeriesMediaCodec>();
            this.tblTVSeriesMediaReleaseTypes = new HashSet<tblTVSeriesMediaReleaseType>();
            this.tblTVSeriesMediaResolutions = new HashSet<tblTVSeriesMediaResolution>();
            this.tblTVSeriesMediaSpecials = new HashSet<tblTVSeriesMediaSpecial>();
        }
    
        public long ID_Media { get; set; }
        public string Media { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaAudio> tblEpisodeMediaAudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaCodec> tblEpisodeMediaCodecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaReleaseType> tblEpisodeMediaReleaseTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaResolution> tblEpisodeMediaResolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaSpecial> tblEpisodeMediaSpecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSery> tblTVSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMovie> tblMovies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaAudio> tblTVSeriesMediaAudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaCodec> tblTVSeriesMediaCodecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaReleaseType> tblTVSeriesMediaReleaseTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaResolution> tblTVSeriesMediaResolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaSpecial> tblTVSeriesMediaSpecials { get; set; }
    }
}
