//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMovie()
        {
            this.tblActors = new HashSet<tblActor>();
            this.tblGenres = new HashSet<tblGenre>();
            this.tblMusics = new HashSet<tblMusic>();
            this.tblProducers = new HashSet<tblProducer>();
            this.tblStudios = new HashSet<tblStudio>();
        }
    
        public long ID_Movie { get; set; }
        public Nullable<int> CollectionNumber { get; set; }
        public string Title { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public Nullable<System.DateTime> Length { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Watched { get; set; }
        public Nullable<bool> Wished { get; set; }
        public string Country { get; set; }
        public Nullable<long> FK_ParentalRating { get; set; }
        public string Language { get; set; }
        public Nullable<bool> Subtitles { get; set; }
        public Nullable<long> FK_Director { get; set; }
        public string IMDBLink { get; set; }
        public string RottenTomatoesLink { get; set; }
        public Nullable<bool> HDREnabled { get; set; }
        public Nullable<bool> C3D { get; set; }
        public Nullable<bool> ReDownload { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<long> FK_Media { get; set; }
        public Nullable<long> FK_Resolution { get; set; }
        public Nullable<long> FK_ReleaseType { get; set; }
        public Nullable<long> FK_Codec { get; set; }
        public Nullable<long> FK_Audio { get; set; }
        public Nullable<long> FK_Specials { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        public virtual tblAudio tblAudio { get; set; }
        public virtual tblCodec tblCodec { get; set; }
        public virtual tblDirector tblDirector { get; set; }
        public virtual tblMedia tblMedia { get; set; }
        public virtual tblParentalRating tblParentalRating { get; set; }
        public virtual tblReleaseType tblReleaseType { get; set; }
        public virtual tblResolution tblResolution { get; set; }
        public virtual tblSpecial tblSpecial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActor> tblActors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGenre> tblGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMusic> tblMusics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducer> tblProducers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudio> tblStudios { get; set; }
    }
}
