//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public long ID_Person { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Natinality { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual tblActor tblActor { get; set; }
        public virtual tblComposer tblComposer { get; set; }
        public virtual tblDirector tblDirector { get; set; }
        public virtual tblProducer tblProducer { get; set; }
        public virtual User User { get; set; }
    }
}
