//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResolution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResolution()
        {
            this.tblEpisodeMediaResolutions = new HashSet<tblEpisodeMediaResolution>();
            this.tblMovies = new HashSet<tblMovie>();
            this.tblTVSeriesMediaResolutions = new HashSet<tblTVSeriesMediaResolution>();
        }
    
        public long ID_Resolution { get; set; }
        public string Resolution { get; set; }
        public string Description { get; set; }
        public Nullable<long> FK_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaResolution> tblEpisodeMediaResolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMovie> tblMovies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaResolution> tblTVSeriesMediaResolutions { get; set; }
    }
}
