//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReleaseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReleaseType()
        {
            this.tblEpisodeMediaReleaseTypes = new HashSet<tblEpisodeMediaReleaseType>();
            this.tblMovies = new HashSet<tblMovie>();
            this.tblTVSeriesMediaReleaseTypes = new HashSet<tblTVSeriesMediaReleaseType>();
        }
    
        public long ID_ReleaseType { get; set; }
        public string ReleaseType { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public Nullable<long> FK_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisodeMediaReleaseType> tblEpisodeMediaReleaseTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMovie> tblMovies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaReleaseType> tblTVSeriesMediaReleaseTypes { get; set; }
    }
}
