//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTVSery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTVSery()
        {
            this.tblEpisodes = new HashSet<tblEpisode>();
            this.tblTVSeriesMediaAudios = new HashSet<tblTVSeriesMediaAudio>();
            this.tblTVSeriesMediaCodecs = new HashSet<tblTVSeriesMediaCodec>();
            this.tblTVSeriesMediaReleaseTypes = new HashSet<tblTVSeriesMediaReleaseType>();
            this.tblTVSeriesMediaResolutions = new HashSet<tblTVSeriesMediaResolution>();
            this.tblTVSeriesMediaSpecials = new HashSet<tblTVSeriesMediaSpecial>();
            this.tblActors = new HashSet<tblActor>();
            this.tblDirectors = new HashSet<tblDirector>();
            this.tblGenres = new HashSet<tblGenre>();
            this.tblMusics = new HashSet<tblMusic>();
            this.tblNetworks = new HashSet<tblNetwork>();
            this.tblProducers = new HashSet<tblProducer>();
            this.tblStudios = new HashSet<tblStudio>();
        }
    
        public long ID_TVSeries { get; set; }
        public string SeriesName { get; set; }
        public Nullable<int> EpisodeCount { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Wished { get; set; }
        public string Country { get; set; }
        public Nullable<long> ID_ParentalRating { get; set; }
        public string Language { get; set; }
        public string IMDBLink { get; set; }
        public string RottenTomatoesLink { get; set; }
        public Nullable<bool> HDREnabled { get; set; }
        public Nullable<bool> C3D { get; set; }
        public Nullable<bool> ReDownload { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Watched { get; set; }
        public byte[] Poster { get; set; }
        public string Size { get; set; }
        public string Length { get; set; }
        public string Subtitles { get; set; }
        public Nullable<long> FK_Media { get; set; }
        public Nullable<long> FK_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEpisode> tblEpisodes { get; set; }
        public virtual tblMedia tblMedia { get; set; }
        public virtual tblParentalRating tblParentalRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaAudio> tblTVSeriesMediaAudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaCodec> tblTVSeriesMediaCodecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaReleaseType> tblTVSeriesMediaReleaseTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaResolution> tblTVSeriesMediaResolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTVSeriesMediaSpecial> tblTVSeriesMediaSpecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActor> tblActors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDirector> tblDirectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGenre> tblGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMusic> tblMusics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNetwork> tblNetworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducer> tblProducers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudio> tblStudios { get; set; }
    }
}
